version: 2.1
orbs:
  node: circleci/node@5.0.2
jobs:
  wikipedia-unit-tests:
    docker:
      - image: "cimg/base:stable"
    steps:
      - checkout
      - node/install:
          node-version: "14.19"
      - node/install-packages
      - run:
          command: npm run lint
      - run:
          command: npm run test
workflows:
  wikipedia-unit-tests:
    jobs:
      - wikipedia-unit-tests